export class ServicioNoDisponibleError extends Error {}
export class HorarioNoDisponibleError extends Error {}
export class TurnoNoEncontradoError extends Error {}
export class TurnoNoModificableError extends Error {}
export class FueraDeVentanaError extends Error {}
export class TurnoYaTieneEmailError extends Error {}
export class CredencialesInvalidasError extends Error {}
export class AdministradorNoEncontradoError extends Error {}
export class PasswordActualIncorrectaError extends Error {}
export class ServicioNoEncontradoError extends Error {}
export class BloqueoNoEncontradoError extends Error {}
export class FeriadoNoEncontradoError extends Error {}
export class FranjaInvalidaError extends Error {}
